name: JLC Auto Sign

on:
  schedule:
    - cron: '0 16,22,4,10 * * *'  # 每 6 小时执行一次，UTC 时间

  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pip install random-user-agent
        
    - name: Run Sign Script
      env:
        TOKEN_LIST: ${{ secrets.TOKEN_LIST }}
        SEND_KEY_LIST: ${{ secrets.SEND_KEY_LIST }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: |
        python main.py
